### ISSUE TITLE
Weak Cryptographic Hash

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/cf-java-client-sap#132]
https://github.com/SAP/cf-java-client-sap/blob/416c1978a9fa34474ac570806695af7a576f8fba/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/util/CloudUtil.java#L50

Weak cryptographic hashes cannot guarantee data integrity and should not be used in security-critical contexts.

**Comment by boyan-velinov** [comment]
This is not related to security but only for optimization demand. If it is changed, just one optmiziation will be skipped.

**Comment by nictas** [comment]
That piece of code has since been deleted.
