### ISSUE TITLE
Path Traversal

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/cf-java-client-sap#66]
hello：
         we found a problem in cf-java-client-sap about Path Traversal.Its uses external input to construct a pathname that should be within a restricted directory, but it does not properly neutralize sequences such as ".." that can resolve to a location that is outside of that directory.In code line 206,if  "entry.getName()" contains “..”  and “/”，this allows attackers to traverse the file system to access files or directories that are outside of the restricted directory. 
![image](https://user-images.githubusercontent.com/39950310/59421749-b425d300-8e01-11e9-9a9e-24770ec5edce.png)

**Comment by nictas** [comment]
This code has since been removed.
